# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecuter.proto\x12\x08\x65xecuter\"5\n\tQueryData\x12\x14\n\x0cnode_id_from\x18\x01 \x01(\x04\x12\x12\n\nnode_id_to\x18\x02 \x01(\x04\"E\n\rQueryFinished\x12\x1e\n\x11shortest_path_len\x18\x01 \x01(\x04H\x00\x88\x01\x01\x42\x14\n\x12_shortest_path_len2M\n\x08\x45xecuter\x12\x41\n\x11ShortestPathQuery\x12\x13.executer.QueryData\x1a\x17.executer.QueryFinishedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYDATA._serialized_start=28
  _QUERYDATA._serialized_end=81
  _QUERYFINISHED._serialized_start=83
  _QUERYFINISHED._serialized_end=152
  _EXECUTER._serialized_start=154
  _EXECUTER._serialized_end=231
# @@protoc_insertion_point(module_scope)
